# Generated by Django 5.0.2 on 2024-04-05 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kikobaApp', '0004_customerprofile_registration'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Registration',
            new_name='Completed_Registration',
        ),
    ]
