# Generated by Django 5.0.2 on 2024-04-08 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kikobaApp', '0005_rename_registration_completed_registration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerprofile',
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Completed_Registration',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='CustomerProfile',
        ),
    ]
